name: Build Mod
on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'

      - name: Create Project and Build
        run: |
          dotnet new classlib -n CinderboxSmartClick
          dotnet add CinderboxSmartClick/CinderboxSmartClick.csproj package Pathoschild.Stardew.ModBuildConfig
          copy ModEntry.cs CinderboxSmartClick\ModEntry.cs
          dotnet build CinderboxSmartClick/CinderboxSmartClick.csproj -c Release

      - name: Upload Finished Mod
        uses: actions/upload-artifact@v3
        with:
          name: CinderboxSmartClick-DLL
          path: CinderboxSmartClick/bin/Release/net6.0/CinderboxSmartClick.dll
          
