name: Build Mod
on: 
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'

      - name: Create and Build Project
        run: |
          dotnet new classlib -n CinderboxSmartClick
          dotnet add CinderboxSmartClick/CinderboxSmartClick.csproj package Pathoschild.Stardew.ModBuildConfig
          copy ModEntry.cs CinderboxSmartClick\ModEntry.cs
          dotnet build CinderboxSmartClick/CinderboxSmartClick.csproj -c Release

      - name: Upload DLL
        uses: actions/upload-artifact@v4
        with:
          name: CinderboxSmartClick-DLL
          path: CinderboxSmartClick/bin/Release/net6.0/CinderboxSmartClick.dll
          
